name: CI Docker Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      #      - name: Cache Docker layers
      #        uses: actions/cache@v2
      #        with:
      #          path: /tmp/.buildx-cache
      #          key: ${{ runner.os }}-buildx-${{ github.sha }}
      #          restore-keys: |
      #            ${{ runner.os }}-buildx-
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: thebigg1/p5js_sketching:latest
      #          cache-from: type=local,src=/tmp/.buildx-cache
      #          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} && ls

#      - uses: actions/upload-artifact@v2
#        with:
#          name: ${{ github.job }}
#          path: bin/*
#          retention-days: 14
  Deploy:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    container:
      image: thebigg1/p5js_sketching:latest
    steps:
      - name: Deps
        run: apt-get update && apt-get install -y git-lfs
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install rsync 📚 
        run: apt-get update && apt-get install -y rsync
            
      - name: Configure git to trust the workspace despite the different owner
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: "Move Directories"
        run: "ls /p5js_sketching"
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: /p5js_sketching/dist # The folder the action should deploy.

